[workspace]
resolver = "2"
members = ["snoopy", "snoopy-common", "snoopy-ebpf"]
default-members = ["snoopy", "snoopy-common"]

[workspace.dependencies]
aya = { version = "0.13.1", default-features = false }
aya-build = { version = "0.1.2", default-features = false }
aya-ebpf = { version = "0.1.1", default-features = false }
aya-log = { version = "0.2.1", default-features = false }
aya-log-ebpf = { version = "0.1.1", default-features = false }

anyhow = { version = "1.0.98", default-features = false }
# `std` feature is currently required to build `clap`.
#
# See https://github.com/clap-rs/clap/blob/61f5ee5/clap_builder/src/lib.rs#L15.
clap = { version = "4.5.36", features = ["derive"] }
env_logger = { version = "0.11.8", default-features = false }
libc = { version = "0.2.171", default-features = false }
log = { version = "0.4.27", default-features = false }
tokio = { version = "1.44.2", default-features = false }
which = { version = "7.0.3", default-features = false }
crossbeam = "0.8.4"
pnet = { version = "0.35.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }

[profile.release]
lto = true
panic = "abort"

[profile.release.package.snoopy-ebpf]
debug = 2
codegen-units = 1

[profile.release.package.snoopy]
codegen-units = 1
opt-level = "z"
strip = "symbols"
