[package]
name = "snoopy-ebpf"
version = "0.1.0"
edition = "2024"

[dependencies]
snoopy-common = { path = "../snoopy-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "snoopy"
path = "src/main.rs"
