[package]
name = "snoopy-common"
version = "0.1.0"
edition = "2024"

[features]
default = []
user = ["aya"]
serde = ["dep:serde"]

[dependencies]
aya = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }

[lib]
path = "src/lib.rs"
