name: Build and Push
on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    runs-on: MEGA-FAST
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Semantic Release
      id: semantic_release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build -t snoppy:latest .
    
    - name: Create output directory for binaries
      run: mkdir -p output
    
    - name: Extract binaries from Docker image
      run: |
        container_id=$(docker create snoppy:latest)
        docker cp $container_id:/usr/local/bin/snoopy_x86_64-unknown-linux-musl ./output/snoopy_x86_64
        docker cp $container_id:/usr/local/bin/snoopy_aarch64-unknown-linux-musl ./output/snoopy_aarch64
        docker cp $container_id:/usr/local/bin/snoopy_riscv64-unknown-linux-musl ./output/snoopy_riscv64
        docker cp $container_id:/usr/local/bin/snoopy_powerpc64le-unknown-linux-musl ./output/snoopy_powerpc64le
        docker cp $container_id:/usr/local/bin/snoopy_armv7-unknown-linux-musleabi ./output/snoopy_armv7
        docker rm $container_id
    
    - name: Release
      uses: softprops/action-gh-release@v2
      if: ${{ steps.semantic_release.outputs.new_release_published }} # only run if a new release is published
      with:
        tag_name: v${{ steps.semantic_release.outputs.new_release_version }}
        files: |
          ./output/*
